### ISSUE TITLE
No environment variables created after authenticating with an API (Netlify Graph - API Authentication)

### ISSUE THREAD

**Issue by baymarket96** [netlify/labs#17]
I was following along with the documentation for Netlify Graph [here](https://github.com/netlify/labs/blob/main/features/graph/documentation/api-authentication.md)

Under the Getting Started section, after connecting to one of the providers (Spotify) and authenticating with it, I had no new environment variables created (after checking Settings > Build & Deploy > Environment), although I'm certain I've completed all steps directly. 

Are there additional steps I need to take not written in the documentation?

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
