### ISSUE TITLE
Immediate issue with Spotify authentication

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/labs#21]
When trying to add Spotify to Netlify Graph, I entered a client id and secret for an app I had built a few months ago. When I tried to enable it in the Netlify dashboard I got:

INVALID_CLIENT: Invalid redirect URI

In the pop up window. So maybe my Spotify app has settings where the id/secret won't work, but how do I know what _should_ be set there? So for example, do I need to make a new app in the Spotify dashboard and use a Netlify specific redirect url? If so - where do I get it?

**Comment by lachieh** [comment]
I had this issue also, but resolved it by adding the following redirect url in my app settings in the [Spotify Developer Dashboard](https://developer.spotify.com/dashboard/applications):
```
https://graph.netlify.com/oauth/receive
```

This is what it should look like:
![Screen Shot 2022-03-20 at 7 15 36 PM](https://user-images.githubusercontent.com/1687902/159190235-1b8c3387-10db-447b-88e4-30952d4da87d.png)

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
