### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jrmeland** [netlify/labs#24]
Hi, I was looking at the new graph feature and saw there are some broken links. Thought I would let you know.

I was on:
https://github.com/netlify/labs/blob/main/features/graph/documentation/README.md

And here is one of the broken links:
`[Start a local CLI session with Netlify Dev](https://github.com/netlify/labs/blob/main/features/graph/documentation/authentication.md#start-a-local-cli-session-with-netlify-dev)`.

Thanks!

**Comment by ClaytonFarr** [comment]
These links are currently broken as well -

- The "gravity" repo links within the "Example repo and tutorial" section.
- All of the links in the "Get started with Netlify Graph" list

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey). For docs-specific feedback, you can use the feedback form at the bottom of the docs page.
