### ISSUE TITLE
Unable to fetch enabled services for site for code generation

### ISSUE THREAD

**Issue by timgriff84** [netlify/labs#25]
Tried a setup with Contentful but immediately ran into an issue.

Steps to reproduce:
1. Created site in Netfily using nextjs template.
2. In Netlify under graph enabled content ful api
3. Cloned repo locally
4. Ran npm install
5. Ran npm install netlify-cli -g
6. Ran netlify link and selected site
7. Ran netlify dev --graph
8. Error "Warning: Unable to fetch enabled services for site for code generation" repeats and session never appears in Netlify.

![Unable to fetch services](https://user-images.githubusercontent.com/5212530/154221253-855b1893-a759-40c9-b0ef-fbf1c2e17000.jpg)

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
