### ISSUE TITLE
netlify graph env variable doesn't exist in production deploy

### ISSUE THREAD

**Issue by buggyhunter** [netlify/labs#26]
Steps to reproduce:
* Enable Netlify graph
* Enable spotify API  & authenticate
* try in local dev environment `netlify dev --graph` , everything works
* try `netlify build` , after deployment finishes, try in prod URL then it gives bad request errors because `ONEGRAPH_AUTHLIFY_TOKEN` is missing.

**Comment by localden** [comment]
For reference for the Graph team, this is related to an internal issue that we're tracking: https://github.com/netlify/netlify-graph-project-planning/issues/51.

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
