### ISSUE TITLE
Issue with auth failing randomly

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/labs#28]
I added auth for Spotify and designed a query. I then exported the handler. When I test, it runs right about half the time, and then the other half gives me an error:

```
Missing auth for Spotify. Please reauthenticate.
```

There seems to be no rhyme nor reason for it going back and forth like that.

**Comment by cfjedimaster** [comment]
It's possible this is a `ntl dev` only issue. In production, it *seems* to always work: https://www.raymondcamden.com/api/latestTracks

**Comment by ekafyi** [comment]
I have the same issue. In my case it _seems_ to occur mostly when running `NetlifyGraph.fetchFoo()` from Remix's `action` handler (ie. as a result of form POST request) as opposed to the `loader`.

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
