### ISSUE TITLE
Exported filename didn't match query name

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/labs#29]
When I first exported, I noticed it used the name of my query for the file name (ExampleQuery.js I believe). I renamed my query, saved, exported again, and the filename didn't change. I navigated away from the editor, and back in, exported again, and it worked right.

**Comment by localden** [comment]
Interesting. @cfjedimaster - are you running `netlify --dev graph` or are you using `netlify graph:edit` and `netlify graph:pull`?

**Comment by cfjedimaster** [comment]
I was using `--dev graph`.

**Comment by cfjedimaster** [comment]
Yep, seems good now. (Btw above I didn't mean to type --dev, it's just dev of course. :)
