### ISSUE TITLE
[question] Can Graph Authentication be used for multiple-user accounts?

### ISSUE THREAD

**Issue by ClaytonFarr** [netlify/labs#32]
Love the possibilities the Graph project is opening up and am excited to see how it develops.

**Will Graph Authentication allow connecting to APIs and managing tokens for multiple user accounts?**

For example - a Salesforce plugin app that users connect to their accounts that then maintains required auth to access and update their individual accounts?

**Comment by ClaytonFarr** [comment]
Hi @sgrove  - Yep, that's correct; and same for other connected services connected to a user's account, e.g. Hubspot.

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
