### ISSUE TITLE
Incorrect sample code in Netlify Graph Explorer web interface

### ISSUE THREAD

**Issue by ekafyi** [netlify/labs#34]
The Netlify Graph Explorer shows a code snippet for our queries, mutations, etc. It currently shows the incorrect method for Mutations, `netlifyGraph.fetchExampleMutation`.

![Screen Shot 2022-02-26 at 18 56 34](https://user-images.githubusercontent.com/6597211/155842274-7883874e-80ca-47a2-a2b8-9e61156828f8.png)

The code from "Generate Handler" action has the correct method, `netlifyGraph.executeExampleMutation`.

**Comment by sgrove** [comment]
Great catch! Should have a fix out for this soon!

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
