### ISSUE TITLE
Netlify Graph/Netlify CLI logging into 1 account and opens a Netlify UI session in another account

### ISSUE THREAD

**Issue by Fran-A-Dev** [netlify/labs#40]
I experienced an issue where I did not realize in my netlify cli I was logged in with one email and then in the Netlify UI, I was logged in as a different user with a different email.  When I opened up a session in my terminal and clicked the link to go to the UI session in the browser it would just cause a blank session page with no GraphQL IDE.  

@sgrove Helped me figure this out and I switched to the correct email login and it fixed.  The error message was not clear on what the issue was.  Thanks again Sean!

**Comment by rstavchansky** [comment]
Hey @Fran-A-Dev! Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey) (or submit feedback internally).
