### ISSUE TITLE
Scheduled Function timeout

### ISSUE THREAD

**Issue by brnpimentel** [netlify/labs#41]
I'm trying this new Netlify featured "Scheduled Function". 

But all my functions timed out on 10seconds. Can i increase this timeout?

**Comment by rstavchansky** [comment]
Currently, Scheduled Functions are executed as synchronous functions, so the default 10-second timeout applies. This is likely to change and we'll allow longer executions, but there's no concrete timeline yet.

We are working on adding this information to the docs now that they've moved over to docs.netlify.com.

If you have other feedback or questions about Scheduled Functions, please post in our [Support Forums](https://answers.netlify.com/) or open an issue in the [netlify/functions repo](https://github.com/netlify/functions). We are archiving this repository now that the docs have moved to our main docs site.
