### ISSUE TITLE
Incorrect Import for 'buffer'

### ISSUE THREAD

**Issue by lachieh** [netlify/labs#43]
I'm currently building a Remix app which uses esbuild. I'm having an issue using the generated `netlifyGraph/index.js` file because there is no default export for the 'buffer' core node module and the esbuild polyfills have a problem with that.

```
✘ [ERROR] No matching export in "node-modules-polyfills:buffer" for import "default"

    netlify/functions/netlifyGraph/index.js:2:7:
      2 │ import buffer from 'buffer'
        ╵        ~~~~~~
```

The problem is fixed by making the following change:

```diff
// GENERATED VIA NETLIFY AUTOMATED DEV TOOLS, EDIT WITH CAUTION!
- import buffer from 'buffer'
+ import * as buffer from 'buffer'
import crypto from 'crypto'
import https from 'https'
import process from 'process'
```

This solution works for the time being, but I have to remember to re-apply the change whenever I make a change to a query through the graph explorer which can be annoying.

Thanks for all the work!

**Comment by rstavchansky** [comment]
Thanks for this feedback. We are archiving this repo now that these docs have moved over to docs.netlify.com. If you have further feedback on Netlify Graph, please fill out our [survey](https://ntl.fyi/apiauthsurvey).
